function [t, vec] = loadAttitude_quat(prefix, instance, basePath)
# load CSV file generated by ulog2csv

filename = [basePath prefix "vehicle_attitude_" num2str(instance) ".csv"];
printf ("input file: %s\n", filename);

A = importdata(filename, ',', 1);
fieldNames = strsplit(A.textdata{1}, ',');
data = csvread(filename);
printf("number of data records: %d\n", size(data)(1));

# using A.colheaders, construct timestamp and x,y,z vectors
tname = "timestamp";
q0name = ["q[0]"];
q1name = ["q[1]"];
q2name = ["q[2]"];
q3name = ["q[3]"];
for i=1:size(A.colheaders)(2)
  if (strcmp(tname, A.colheaders(i))) tindex = i; endif
  if (strcmp(q0name, A.colheaders(i))) q0index = i; endif
  if (strcmp(q1name, A.colheaders(i))) q1index = i; endif
  if (strcmp(q2name, A.colheaders(i))) q2index = i; endif
  if (strcmp(q3name, A.colheaders(i))) q3index = i; endif
endfor

t = A.data(:,tindex) / 1e6;
vec = [A.data(:,q0index) A.data(:,q1index) A.data(:,q2index) A.data(:,q3index)];

end