function plotRF(basePath, file)
# plot CSV file generated by rfe.py

data = dlmread([basePath "/" file],',',0, 12);
figure()
imshow(gray2ind((data+100)/max(max(data+100)),256))
figure()
waterfall(data)

end
