function [t, vec] = loadControlGroup0(prefix, instance, basePath)
# load CSV file generated by ULogReader

filename = [basePath prefix "actuator_controls_0_" num2str(instance) ".csv"];
printf ("input file: %s\n", filename);

data = tdfread(filename);
t = data.timestamp / 1e6;
vec = [data.control_0_, data.control_1_, data.control_2_];

end