function [t, vec] = loadVratesSP(prefix, instance, basePath)
# load CSV file generated by ULogReader

filename = [basePath prefix "vehicle_rates_setpoint_" num2str(instance) ".csv"];
printf ("input file: %s\n", filename);

data = tdfread(filename);
t = data.timestamp / 1e6;
vec = [data.roll, data.pitch, data.yaw];

end
