function [t, vec] = loadAttitude_quat(prefix, instance, basePath)
# load CSV file generated by ulog2csv

filename = [basePath prefix "vehicle_attitude_" num2str(instance) ".csv"];
printf ("input file: %s\n", filename);

data = tdfread(filename);
t = data.timestamp / 1e6;
vec = [data.q_0_, data.q_1_, data.q_2_, data.q_3_];

end
