function [t, vec] = loadGyro_int(prefix, instance, basePath)
# load CSV file generated by ULogReader

filename = [basePath prefix "sensor_gyro_" num2str(instance) ".csv"];
printf ("input file: %s\n", filename);

data = tdfread(filename);
t = data.timestamp / 1e6;
vec = [data.x_integral, data.y_integral, data.z_integral];
vec = vec ./ data.integral_dt;

end
