function [t, gyro, rsp, rpy, asp, data] = loadSID(basePath)
# load CSV file generated by mavlogdump.py

data = tdfread([basePath "/sid.csv"]);
t = 1e-6 * data.TimeUS;
gyro = [data.GX, data.GY, data.GZ];
rsp = [data.RX, data.RY, data.RZ];
rpy = [data.R, data.P, data.Y];
asp = [data.AX, data.AY, data.AZ];

end
