function [t, gyro, sp, data] = loadGRSP(basePath)
# load CSV file generated by mavlogdump.py

data = tdfread([basePath "/grsp.csv"]);
t = 1e-6 * data.TimeUS;
gyro = [data.GyrX, data.GyrY, data.GyrZ];
sp = [data.spX, data.spY, data.spZ];

end
