function [t, vec] = loadAccel_raw(prefix, instance, basePath)
# load CSV file generated by ULogReader

filename = [basePath prefix "sensor_accel_" num2str(instance) ".csv"];
printf ("input file: %s\n", filename);

data = tdfread(filename);
t = data.timestamp / 1e6;
vec = [data.x_raw, data.y_raw, data.z_raw];

end
